# Generated by Django 3.2.6 on 2022-11-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del deporte')),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'db_table': 'deportes',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('deporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.deporte')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'disciplina',
                'db_table': 'disciplinas',
            },
        ),
    ]
