# Generated by Django 3.2.6 on 2022-11-26 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='disciplina_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.disciplina'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=250, verbose_name='Resultado')),
                ('observaciones', models.CharField(max_length=10000, verbose_name='Observaciones')),
                ('atleta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.atleta')),
            ],
            options={
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
                'db_table': 'partidos',
            },
        ),
    ]
